export const getAllTablesData = () => {
    const people = [
        { name: 'Алексей', secondName: 'Петров', experience: 5, profession: 'Программист', hobby: 'Чтение' },
        { name: 'Мария', secondName: 'Иванова', experience: 3, profession: 'Дизайнер', hobby: 'Рисование' },
        { name: 'Иван', secondName: 'Сидоров', experience: 7, profession: 'Тестировщик', hobby: 'Видеоигры' },
        { name: 'Елена', secondName: 'Кузнецова', experience: 12, profession: 'Менеджер', hobby: 'Путешествия' },
        { name: 'Дмитрий', secondName: 'Орлов', experience: 8, profession: 'Инженер', hobby: 'Фотография' },
        { name: 'Светлана', secondName: 'Смирнова', experience: 10, profession: 'Аналитик', hobby: 'Кулинария' },
        { name: 'Константин', secondName: 'Лебедев', experience: 6, profession: 'Архитектор', hobby: 'Футбол' },
        { name: 'Анна', secondName: 'Васильева', experience: 2, profession: 'Психолог', hobby: 'Медитация' },
        { name: 'Николай', secondName: 'Ковалев', experience: 15, profession: 'Врач', hobby: 'Велосипед' },
        { name: 'Ольга', secondName: 'Козлова', experience: 4, profession: 'Учитель', hobby: 'Плавание' },
        { name: 'Андрей', secondName: 'Федоров', experience: 9, profession: 'Юрист', hobby: 'Музыка' },
        { name: 'Вера', secondName: 'Волкова', experience: 11, profession: 'Журналист', hobby: 'Писательство' },
        { name: 'Максим', secondName: 'Попов', experience: 5, profession: 'Водитель', hobby: 'Рыбалка' },
        { name: 'Татьяна', secondName: 'Романова', experience: 3, profession: 'Флорист', hobby: 'Садоводство' },
        { name: 'Павел', secondName: 'Кузьмин', experience: 7, profession: 'Строитель', hobby: 'Карате' },
        { name: 'Лариса', secondName: 'Соловьева', experience: 13, profession: 'Маркетолог', hobby: 'Шитье' },
        { name: 'Владимир', secondName: 'Яковлев', experience: 16, profession: 'Агроном', hobby: 'Флористика' },
        { name: 'Оксана', secondName: 'Зайцева', experience: 2, profession: 'Тренер', hobby: 'Фитнес' },
        { name: 'Сергей', secondName: 'Савельев', experience: 14, profession: 'Пожарный', hobby: 'Скалолазание' },
        { name: 'Жанна', secondName: 'Тимофеева', experience: 6, profession: 'Бухгалтер', hobby: 'Кулинария' },
        { name: 'Роман', secondName: 'Гусев', experience: 3, profession: 'Кинолог', hobby: 'Собаководство' },
        { name: 'Виктория', secondName: 'Логинова', experience: 9, profession: 'Стоматолог', hobby: 'Теннис' },
        { name: 'Евгений', secondName: 'Воробьев', experience: 4, profession: 'Бариста', hobby: 'Рисование' },
        { name: 'Алла', secondName: 'Сафонова', experience: 10, profession: 'Парикмахер', hobby: 'Шахматы' },
        { name: 'Григорий', secondName: 'Прохоров', experience: 8, profession: 'Официант', hobby: 'Путешествия' },
        { name: 'Алена', secondName: 'Королева', experience: 2, profession: 'Продавец', hobby: 'Фотография' },
        { name: 'Игорь', secondName: 'Климов', experience: 15, profession: 'Писатель', hobby: 'Каякинг' },
        { name: 'Юлия', secondName: 'Дмитриева', experience: 11, profession: 'Хореограф', hobby: 'Танцы' },
        { name: 'Федор', secondName: 'Горбачев', experience: 7, profession: 'Судья', hobby: 'Скалолазание' },
        { name: 'Наталья', secondName: 'Гончарова', experience: 3, profession: 'Кассир', hobby: 'Скейтбординг' },
        { name: 'Аркадий', secondName: 'Чернов', experience: 9, profession: 'Сценарист', hobby: 'Косплей' },
        { name: 'Валерия', secondName: 'Макарова', experience: 6, profession: 'Экономист', hobby: 'Йога' },
        { name: 'Степан', secondName: 'Селиванов', experience: 4, profession: 'Инструктор', hobby: 'Волейбол' },
        { name: 'Зоя', secondName: 'Михайлова', experience: 12, profession: 'Библиотекарь', hobby: 'Шахматы' },
        { name: 'Геннадий', secondName: 'Беляев', experience: 10, profession: 'Электрик', hobby: 'Садоводство' },
        { name: 'Карина', secondName: 'Ершова', experience: 8, profession: 'Массажист', hobby: 'Кулинария' },
        { name: 'Олег', secondName: 'Калашников', experience: 5, profession: 'Режиссер', hobby: 'Поэзия' },
        { name: 'Вероника', secondName: 'Самойлова', experience: 2, profession: 'Логопед', hobby: 'Йога' },
        { name: 'Михаил', secondName: 'Широков', experience: 7, profession: 'Фармацевт', hobby: 'Аквариумистика' },
        { name: 'Полина', secondName: 'Якимова', experience: 3, profession: 'Животновод', hobby: 'Садоводство' },
        { name: 'Лев', secondName: 'Цветков', experience: 13, profession: 'Реаниматолог', hobby: 'Сноуборд' },
        { name: 'Станислав', secondName: 'Трофимов', experience: 4, profession: 'Плотник', hobby: 'Авто' },
        { name: 'Дарья', secondName: 'Щербакова', experience: 12, profession: 'Учитель', hobby: 'Лыжи' },
        { name: 'Арсений', secondName: 'Шишкин', experience: 14, profession: 'Охотник', hobby: 'Рыбалка' },
        { name: 'Маргарита', secondName: 'Морозова', experience: 6, profession: 'Фитнес-тренер', hobby: 'Бег' },
        { name: 'Виталий', secondName: 'Жуков', experience: 5, profession: 'Программист', hobby: 'Гейминг' },
        { name: 'Инна', secondName: 'Алексеева', experience: 2, profession: 'Психолог', hobby: 'Медитация' },
        { name: 'Виктор', secondName: 'Рудин', experience: 10, profession: 'Плотник', hobby: 'Фигурное катание' },
        { name: 'Олеся', secondName: 'Маслова', experience: 3, profession: 'Модельер', hobby: 'Фотография' },
        { name: 'Борис', secondName: 'Янковский', experience: 9, profession: 'Фотограф', hobby: 'Астрономия' }
    ];


    return people;
}